### ISSUE TITLE
suggest: read the geom with wkb::readWKB

### ISSUE THREAD

**Issue by mdsumner** [SESYNC-ci/postGIStools#3]
Wondering if you can do the read direct from the binary rather than casting to WKT? I use an approach like this to read from Manifold GIS, you just use SQL to cast the native binary to WKB and get that directly into an R 'raw' vector.  (Maybe can't issue queries to Postgres that return raw vectors for R? )

``` R
## pseudo code

qu <-  "SELECT name, iso2, capital, population,
              ST_AsBinary(geom) AS WKB 
              FROM country 
                WHERE population > 1000000")

tab <- RPostgreSQL::dbGetQuery(conn, qu)

geom <- wkb::readWKB(tab$WKB)
tab$WKB <- NULL

sp <- SpatialPolygonsDataFrame(geom, tab, match.ID = FALSE)
```

I don't have PostGIS to actually do this but I'm hoping to, very keen to see more tools like this.  

See Examples section under "Manifold geometry via RODBC" where the CGeomWKB function is used to convert from native to WKB.

**Comment by pmarchand1** [comment]
Thanks for this idea. I did not know about the 'wkb' package. With RPostgreSQL, binary columns (PostgreSQL type 'bytea') are returned as hexstrings rather than raw in R, but they can still be converted with an extra step, i.e. `readWKB(hex2raw(tab$WKB))`.

Based on the tests below, it seems the binary query is faster on the SQL side; however, by far the longest step is converting the output to sp. types, and readWKT is faster than readWKB (probably because of the underlying C implementation of GEOS).

```
library(RPostgreSQL)
library(rgeos)
library(wkb)

con <- dbConnect(PostgreSQL(), dbname = "d2u06to89nuqei", user = "mzcwtmyzmgalae",
                 host = "ec2-107-22-246-250.compute-1.amazonaws.com",
                 password = "UTv2BuwJUPuruhDqJthcngyyvO")

system.time(replicate(10,
                      dbGetQuery(con, "SELECT name, iso2, ST_AsText(geom) FROM country")))
>   user  system elapsed 
>  0.184   0.009   0.736

system.time(replicate(10, 
           dbGetQuery(con, "SELECT name, iso2, encode(ST_AsBinary(geom), 'hex') 
                            AS geom_wkb FROM country")))
>   user  system elapsed 
>  0.213   0.045   0.391

wkt_load <- function() {
    wkt_out <- dbGetQuery(con,
        "SELECT name, iso2, ST_AsText(geom) AS geom_wkt FROM country" 
    )
    do.call(rbind, Map(readWKT, text = wkt_out$geom_wkt, 
                       id = 1:nrow(wkt_out), USE.NAMES = FALSE))
}

wkb_load <- function() {
    wkb_out <- dbGetQuery(con,
        "SELECT name, iso2, encode(ST_AsBinary(geom), 'hex') AS geom_wkb FROM country"
    )
    readWKB(hex2raw(wkb_out$geom_wkb))
}

system.time(replicate(10, wkt_load()))
>   user  system elapsed 
>  3.715   0.003   5.212 
system.time(replicate(10, wkb_load()))
>    user  system elapsed 
> 19.330   0.160  20.028 
```
