### ISSUE TITLE
Fails with ST_MakeEnvelope()

### ISSUE THREAD

**Issue by mem48** [SESYNC-ci/postGIStools#5]
postGIStools will not pass valid PostGIS queries using the ST_MakeEnvelope() function for example

`SELECT id, geom, code FROM oa WHERE geom && ST_MakeEnvelope(-0.11, 51.45, -0.09, 51.5 ,4326)`

Works fine with pgAdminIII but fails with message:

`Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  syntax error at or near "AS"
LINE 1: ..."geom_srid", code FROM oa WHERE ST_AsText("geom") AS "geom_w...
                                                             ^
)
 Error in 1:nrow(res) : argument of length 0`

**Comment by pmarchand1** [comment]
@mem48 Did you update to the newest (0.2.0) version of the package?

**Comment by mem48** [comment]
Yes, I even tried uninstalling and reinstalling the package but still does not work

**Comment by pmarchand1** [comment]
@mem48 I was able to run the following similar query using our test database:

```
library(RPostgreSQL)
library(postGIStools)

con <- dbConnect(PostgreSQL(), dbname = "d2u06to89nuqei", user = "mzcwtmyzmgalae",
                 host = "ec2-107-22-246-250.compute-1.amazonaws.com",
                 password = "UTv2BuwJUPuruhDqJthcngyyvO")

countries <- get_postgis_query(con, "SELECT name, geom FROM country WHERE
                               geom && ST_MakeEnvelope(-70, -55, -65, -53, 4326)",
                               geom_name = "geom")

countries$name
## [1] "Argentina" "Chile" 
```

If you still get an error, you can run the following internal function to see the query text that's actually being sent.

```
postGIStools:::edit_select_query(con, ##your query statement##, 
                                                   geom_name = "geom", hstore_name = NA)
```

I may be able to debug it given the output of that function.

**Comment by mem48** [comment]
I can't connect to that database

```
con <- dbConnect(PostgreSQL(), dbname = "d2u06to89nuqei", user = "mzcwtmyzmgalae", host = "ec2-107-22-246-250.compute-1.amazonaws.com", password = "UTv2BuwJUPuruhDqJthcngyyvO")

Error in postgresqlNewConnection(drv, ...) : 
  RS-DBI driver: (could not connect mzcwtmyzmgalae@ec2-107-22-246-250.compute-1.amazonaws.com on dbname "d2u06to89nuqei"
)
```

**Comment by pmarchand1** [comment]
@mem48 The test database can't be accessed in Windows or OS X. However, what I was suggesting is that you run the postGIStools:::edit_select_query(...) on your own database and paste the output here (which should be a detailed SQL query that's being run by postGIStools).

**Comment by mem48** [comment]
Sorry for the misunderstanding here is the error code

```
> postGIStools:::edit_select_query(con, "SELECT id FROM regions WHERE geom && ST_MakeEnvelope(-2, 50, 1, 52, 4326)",
+ geom_name = "geom", hstore_name = NA)

[1] "SELECT *,ST_AsText(\"geom\") AS \"geom_wkt\", ST_SRID(\"geom\") AS \"geom_srid\" FROM (SELECT id FROM regions WHERE geom && ST_MakeEnvelope(-2, 50, 1, 52, 4326)) baseqry LEFT JOIN spatial_ref_sys ON ST_SRID(\"geom\") = srid;"
```

**Comment by pmarchand1** [comment]
Great, thank you! The `geom_name` needs to be a column that is returned by the query, i.e. the following should work:

```
get_postgis_query(con, "SELECT id, geom FROM regions WHERE 
                                        geom && ST_MakeEnvelope(-2, 50, 1, 52, 4326)", geom_name = "geom")
```

If the output doesn't include any geometry column, you can use:

```
get_postgis_query(con, "SELECT id FROM regions WHERE 
                                        geom && ST_MakeEnvelope(-2, 50, 1, 52, 4326)")
```

though in that case the `dbGetQuery` function from `RPostgreSQL` would give the same results.

**Comment by mem48** [comment]
Thanks it now seems to be working
