### ISSUE TITLE
Support for 2 geoms

### ISSUE THREAD

**Issue by muscatelle** [SESYNC-ci/postGIStools#7]
Given a simple table (
id serial,
geom srid=3857 - google mercator
geom84 srid=4326)

 select id, geom84, geom from tmp_abc_noise 
- returns all three fields when run from pgAdmin
  
  get_postgis_query(con,"select id, geom84, geom from tmp_abc_noise", geom_name="geom84")
  - returns all three fields

But
 get_postgis_query(con,"select id, geom84, geom from tmp_abc_noise", geom_name="geom")
- throws an error:
  Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  syntax error at or near "84"
  LINE 1: ...om") AS "geom_wkt", ST_SRID("geom") AS "geom_srid"84, ST_AsT...                                                             ^
  )
  Error in 1:nrow(res) : argument of length 0

qgis imports the table using either geom

I suspect this may be a bug but please accept my apologies if this is not the case.

**Comment by richardellison** [comment]
Are you using the latest version? I can run the following similar query with two geometry fields without any errors:

``` r
testqry <- get_postgis_query(con, 
"SELECT ts_id, ts_loc, ST_Transform(ts_loc, 3308) AS ts_loc3308 FROM transitstops", 
geom_name = "ts_loc")
```

In an earlier version of the package, queries were constructed in a different way that would sometimes result in what you are seeing, but this should not happen since version 0.2.0.

**Comment by muscatelle** [comment]
Was still using the older version - upgrading has fixed the problem.
Thanks
